baseURL = "https://meritxellma.github.io/"
theme = "universal"    
DefaultContentLanguage = "en"

[params]
    author = "Coneptum S.L."
    logo = "img/logo.png"

    defaultKeywords = []
    defaultDescription = ""

    address = """<p>C/Sant Agustí, 5<br>Barcelona<br>08012<br><br></p>"""

    email = "my.email@my.domain"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    viewMorePostLink = "/blog/"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
   enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.see_more]
    enable = true

[params.carousel]
    enable = true

#defined in data/features
[params.features]
    enable = true

[params.tecnologies]
    enable = true

#defined in data/testimonials
[params.testimonials]
    enable = false

#defined in data/clients
[params.clients]
    enable = true

[params.recent_posts]
    enable = true

[languages]
    [languages.en]
	title = "Coneptum S.L."
	weight = 1
	languagename = "English"
    	copyright = "Copyright english"
    	about_us = "<p>Code are docs</p>"

    	googleMapsApiKey = "AIzaSyATL9vK41Q8XMkzY5KXADt_szjL7cLjP70"

	latitude = "41.3984171"
	longitude = "2.1607018"


	[[languages.en.menu.main]]
	    url = "/"
	    name = "Home"
	    weight = 1
	[[languages.en.menu.main]]
	    url = "/blog/"
	    name = "Blog"
	    weight = 2
	[[languages.en.menu.main]]
    	    name = "Contact"
    	    url  = "/contact/"
    	    weight = 3
	[[languages.en.menu.main]]
    	    name = "Language"
    	    weight = 4
	    identifier = "lang"
	[[languages.en.menu.main]]
	    name = "English"
	    parent = "lang"
	    identifier = "en"
	    url = "/"
	    weight = 1
	[[languages.en.menu.main]]
	    name = "Español"
	    parent = "lang"
	    identifier = "es"
	    url = "/es"
	    weight = 2
	[[languages.en.menu.main]]
	    name = "Català"
	    parent = "lang"
	    identifier = "ca"
	    url = "/ca"
	    weight = 3

	[[languages.en.menu.topbar]]
	    weight = 1
	    name = "GitHub"
	    url = "https://github.com"
	    pre = "<i class='fa fa-2x fa-github'></i>"
	[[languages.en.menu.topbar]]
	    weight = 2
	    name = "Facebook"
	    url = "http://facebook.com"
	    pre = "<i class='fa fa-2x fa-facebook'></i>"
	[[languages.en.menu.topbar]]
	    weight = 3
	    name = "Twitter"
	    url = "http://twitter.com"
	    pre = "<i class='fa fa-2x fa-twitter'></i>"
	[[languages.en.menu.topbar]]
	    weight = 4
	    name = "Email"
	    url = "mailto:your@email.com"
	    pre = "<i class='fa fa-2x fa-envelope'></i>"

    [languages.es]
	title = "Coneptum S.L."
	weight = 2
	languagename = "Español"
    	copyright = "Copyright español"
    	about_us = "<p>La documentación es el código</p>"

    	googleMapsApiKey = "AIzaSyATL9vK41Q8XMkzY5KXADt_szjL7cLjP70"

	latitude = "41.3984171"
	longitude = "2.1607018"

	[[languages.es.menu.main]]
	    url = "/es/"
	    name = "Home"
	    weight = 1
	[[languages.es.menu.main]]
	    url = "/es/blog/"
	    name = "Blog"
	    weight = 2
	[[languages.es.menu.main]]
    	    name = "Contacta"
    	    url  = "/es/contact/"
    	    weight = 3
	[[languages.es.menu.main]]
    	    name = "Idioma"
    	    weight = 4
	    identifier = "lang"
	[[languages.es.menu.main]]
	    name = "English"
	    parent = "lang"
	    identifier = "en"
	    url = "/"
	    weight = 1
	[[languages.es.menu.main]]
	    name = "Español"
	    parent = "lang"
	    identifier = "es"
	    url = "/es"
	    weight = 2
	[[languages.es.menu.main]]
	    name = "Català"
	    parent = "lang"
	    identifier = "ca"
	    url = "/ca"
	    weight = 3

	[[languages.es.menu.topbar]]
	    weight = 1
	    name = "GitHub"
	    url = "https://github.com"
	    pre = "<i class='fa fa-2x fa-github'></i>"
	[[languages.es.menu.topbar]]
	    weight = 2
	    name = "Facebook"
	    url = "http://facebook.com"
	    pre = "<i class='fa fa-2x fa-facebook'></i>"
	[[languages.es.menu.topbar]]
	    weight = 3
	    name = "Twitter"
	    url = "http://twitter.com"
	    pre = "<i class='fa fa-2x fa-twitter'></i>"
	[[languages.es.menu.topbar]]
	    weight = 4
	    name = "Email"
	    url = "mailto:your@email.com"
	    pre = "<i class='fa fa-2x fa-envelope'></i>"
    [languages.ca]
	title = "Coneptum S.L."
	weight = 3
	languagename = "Català"
    	copyright = "Copyright català"
    	about_us = "<p>La documentació és el codi</p>"

    	googleMapsApiKey = "AIzaSyATL9vK41Q8XMkzY5KXADt_szjL7cLjP70"

	latitude = "41.3984171"
	longitude = "2.1607018"

	[[languages.ca.menu.main]]
	    url = "/ca/"
	    name = "Home"
	    weight = 1
	[[languages.ca.menu.main]]
	    url = "/ca/blog/"
	    name = "Blog"
	    weight = 2
	[[languages.ca.menu.main]]
    	    name = "Contacta"
    	    url  = "/ca/contact/"
    	    weight = 3
	[[languages.ca.menu.main]]
    	    name = "Idioma"
    	    weight = 4
	    identifier = "lang"
	[[languages.ca.menu.main]]
	    name = "English"
	    parent = "lang"
	    identifier = "en"
	    url = "/"
	    weight = 1
	[[languages.ca.menu.main]]
	    name = "Español"
	    parent = "lang"
	    identifier = "es"
	    url = "/es"
	    weight = 2
	[[languages.ca.menu.main]]
	    name = "Català"
	    parent = "lang"
	    identifier = "ca"
	    url = "/ca"
	    weight = 3

	[[languages.ca.menu.topbar]]
	    weight = 1
	    name = "GitHub"
	    url = "https://github.com"
	    pre = "<i class='fa fa-2x fa-github'></i>"
	[[languages.ca.menu.topbar]]
	    weight = 2
	    name = "Facebook"
	    url = "http://facebook.com"
	    pre = "<i class='fa fa-2x fa-facebook'></i>"
	[[languages.ca.menu.topbar]]
	    weight = 3
	    name = "Twitter"
	    url = "http://twitter.com"
	    pre = "<i class='fa fa-2x fa-twitter'></i>"
	[[languages.ca.menu.topbar]]
	    weight = 4
	    name = "Email"
	    url = "mailto:your@email.com"
	    pre = "<i class='fa fa-2x fa-envelope'></i>"


