baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hello Hugo"
theme = "universal"

[menu]

# Main menu

[[menu.main]]
	    url = "/"
	    name = "Home"
	    weight = 1

[[menu.main]]
	    url = "/blog/"
	    name = "Blog"
	    weight = 2

[[menu.main]]
    	    name = "Contact"
    	    url  = "/contact/"
    	    weight = 3


# Top bar social links menu
[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 5
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 7
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"


[params]

    author = "Meritxell Martí"
    logo = "img/logo.png"
    style = "green"

    defaultKeywords = []
    defaultDescription = ""

    copyright = "Copyright"

    address = """<p>C/Sant Agustí, 5<br>Barcelona<br>080..<br><br></p>"""
    latitude = "41.3984171"
    longitude = "2.1607018"

    about_us = "<p>La documentació és el  codi</p>"
    email = "my.email@my.domain"

    DefaultContentLanguage = "en"
    defaultContentLanguageInSubdir= true

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    viewMorePostLink = "/blog/"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
   enable = true
   text = "Testing hugo"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

#defined in data/carousel
[params.carousel]
    enable = true

#defined in data/features
[params.features]
    enable = true

[params.see_more]
    enable = true
    icon = "fa fa-smile-o"
    title = "Titol"
    subtitle = "descripció"
    link_url = "http://your-site.com/more"
    link_text = "Més"

#defined in data/testimonials
[params.testimonials]
    enable = true
    title = "Opinions"
    subtitle = ""

#defined in data/clients
[params.clients]
    enable = true
    title = "Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Entrades del blog"
    subtitle = "entrades del blog"


